In [29]:
import cv2
import numpy as np
from imutils.object_detection import non_max_suppression

In [17]:
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

In [23]:
image = cv2.imread('../data/03.jpg')

In [24]:
(rects, weights) = hog.detectMultiScale(image, winStride=(4, 4),padding=(8, 8), scale=1.05)

In [25]:
print rects,weights

[[112  75 175 350]
 [370 108 178 356]
 [448  97 172 344]
 [-15 121 165 329]
 [286 122 170 340]
 [624 118 104 208]] [[ 1.07447296]
 [ 1.49554737]
 [ 0.71027926]
 [ 0.75870468]
 [ 0.19629458]
 [ 0.32214918]]


In [30]:
orig = cv2.imread('../data/03.jpg')
# draw the original bounding boxes
#for (x, y, w, h) in rects:
#   cv2.rectangle(orig, (x, y), (x + w, y + h), (0, 0, 255), 2)
rects = np.array([[x, y, x + w, y + h] for (x, y, w, h) in rects])
pick = non_max_suppression(rects, probs=None, overlapThresh=0.65)
for (xA, yA, xB, yB) in pick:
    cv2.rectangle(orig, (xA, yA), (xB, yB), (0, 255, 0), 2)

In [31]:
cv2.imwrite('../data/03_annot.png',orig)

True

In [59]:
# face detection
face_cascade = cv2.CascadeClassifier('../data/cascades.xml')
type(face_cascade)

cv2.CascadeClassifier

In [138]:
def initCascades():
    cascades = []
    for i in range(9):
        cascades.append(cv2.CascadeClassifier('../data/0'+ str(i+1) + '.xml'))
    return cascades

In [121]:
def applyCascades(cascades,gray,canvas):
    for cascade in cascades:
        rects = cascade.detectMultiScale(gray,1.3,5)
        for (x,y,w,h) in rects:
            cv2.rectangle(canvas,(x,y),(x+w,y+h),(255,0,0),2)
    return canvas

In [125]:
def applyCascade(cascade_name,gray,canvas):
    cascade = cv2.CascadeClassifier('../data/'+cascade_name)
    rects = cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in rects:
        cv2.rectangle(canvas,(x,y),(x+w,y+h),(255,0,0),2)
    return canvas


In [149]:
gray = cv2.imread('../data/02.jpg',0)
canvas = cv2.imread('../data/02.jpg')
#gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
#faces = face_cascade.detectMultiScale(canvas, 1.3, 5)


In [143]:
cascades = initCascades()
canvas = applyCascades(cascades,gray,canvas)

In [150]:
cv2.imwrite('../data/02ann.png',applyCascade('pedestrian.xml',gray,canvas))

True

In [144]:
cv2.imwrite('../data/03_annot.png',canvas)

True

In [151]:
im = cv2.imread('../data/02.jpg')
imhsv = cv2.cvtColor(im,cv2.COLOR_BGR2HSV)

In [155]:
imhsv[:][:][2]

array([[154,  66, 155],
       [154,  66, 154],
       [154,  66, 155],
       ..., 
       [154,  50, 167],
       [154,  50, 168],
       [154,  50, 168]], dtype=uint8)

In [156]:
cv2.imwrite('../data/hsv.png',imhsv)

True

In [161]:
imhsv[:,:,2] = np.median(imhsv[:,:,2])
cv2.imwrite('../data/hsv_.png',imhsv)

True

In [162]:
imrgb = cv2.cvtColor(imhsv,cv2.COLOR_HSV2BGR)
cv2.imwrite('../data/hsv2bgr.png',imrgb)

True